Parameters:
#Secret Access key input parameter for bastion host and app instance
  KeyName:
    Description: Amazon EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
  Tag: 
    Type: "String"
  DBUsername:
    Type: "String" 
  DBPassword:
    Type: "String"   

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0b0dcb5067f052a63 # Amazon instance id
    us-west-1:
      AMI: ami-0f5e8a042c8bfcd5e
    us-east-2:
      AMI: ami-0beaa649c482330f7
    us-west-2:
      AMI: ami-094125af156557ca2     
    eu-west-1:
      AMI: ami-01cae1550c0adea9c
    ap-southeast-1:
      AMI: ami-0af2f764c580cc1f9
    ap-southeast-2:
      AMI: ami-06bb074d1e196d0d4
    ap-south-1:
      AMI: ami-074dc0a6f6c764218
    ca-central-1:
      AMI: ami-0ee679ef733e3b8e7
    eu-central-1:
      AMI: ami-076309742d466ad69
    eu-west-2:
      AMI: ami-04706e771f950937f
    eu-west-3:
      AMI: ami-0f15e0a4c8d3ee5fe
    eu-north-1:
      AMI: ami-02aeff1a953c5c2ff
    sa-east-1:
      AMI: ami-0b7101e993ea27f3

Resources: 
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      InstanceTenancy: "default"
      Tags:
      - Key: "Name"
        Value: !Ref "Tag"

  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: 'AWS::Region'
      VpcId: !Ref "VPC"
      CidrBlock: "10.0.3.0/24"    

  RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"

  VPCGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref "VPC"
      InternetGatewayId: !Ref "InternetGateway"

  InternetRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable

  PublicSubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref PublicSubnet
 

  # JumpBox  
  BastionEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      Tags:
        - Key: Name
          Value: "Bastion Host"
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: BastionHostSecurityGroup
          SubnetId:
            Ref: "PublicSubnet"
  
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      SecurityGroupIds:
        - !Ref AppInstanceSecurityGroup
      SubnetId: !Ref PrivateSubnet
      Tags:
        - Key: Name
          Value: "Private Instance"
      KeyName: !Ref KeyName          
  
  #Security Group of JumpBox
  BastionHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open Port 22 for ssh
      VpcId: !Ref "VPC" 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
  
  #Security Group of AppInstance
  AppInstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: SSH access via port 22 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          SourceSecurityGroupId: !Ref BastionHostSecurityGroup
      Tags:
        - Key: Name
          Value: WebServer Security Group
      VpcId: !Ref VPC

  PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: 'AWS::Region'
      VpcId: !Ref "VPC"
      CidrBlock: "10.0.0.0/24"

  PrivateSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: 'AWS::Region'
      VpcId: !Ref "VPC"
      CidrBlock: "10.0.1.0/24"

  PrivateSubnet3:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs 
          Ref: 'AWS::Region'
      VpcId: !Ref "VPC"
      CidrBlock: "10.0.2.0/24"

  # Database Subnet Group
  SubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: "subnetgroup"
      DBSubnetGroupDescription: "Subnet Group"
      SubnetIds:
      - !Ref "PrivateSubnet2"
      - !Ref "PrivateSubnet3"

  DataBaseSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "Example Security Group"
      GroupDescription: "RDS traffic"
      VpcId: !Ref "VPC"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: "10.0.0.0/16"
      Tags:
        - Key: Name
          Value: DataBase Security Group

  # Amazon RDS Database Instance    
  RDS:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBSubnetGroupName: !Ref "SubnetGroup"
      MasterUsername: !Ref "DBUsername"
      MasterUserPassword: !Ref "DBPassword"
      DBInstanceClass: db.t3.micro
      Engine: "MySQL"
      VPCSecurityGroups: 
      - !Ref DataBaseSecurityGroup
      StorageType: gp2
      AllocatedStorage: 20

Outputs:
  VpcId:
    Description: The VPC ID
    Value: !Ref VPC

  BastionHostIP:
    Description: The Public Ip
    Value: !GetAtt BastionEC2Instance.PublicIp
  PrivateInstanceIp:
    Description: The Private Ip of host
    Value: !GetAtt AppInstance.PrivateIp
  ConnectionCMD:
    Value:
      !Join [
        "",
        [
          ssh -A -J ec2-user@,
          !GetAtt BastionEC2Instance.PublicIp,     #SSh Command to connect to instance
          " ",
          ec2-user@,
          !GetAtt AppInstance.PrivateIp,
        ],
      ]
    Description: Copy and run it in your shell  